#!/bin/bash

# PACE Development - Upstash Redis Quick Reference

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         PACE Development - Upstash Redis Quick Reference      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ UPSTASH REDIS MIGRATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  ✓ Local Redis container has been replaced with Upstash"
echo "  ✓ No startup/shutdown scripts needed"
echo "  ✓ Cache automatically uses cloud-based Redis at Upstash"
echo ""
echo ""

echo "🗑️  CLEAR CACHE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Clear all Upstash cache (with confirmation):"
echo "    🐧 ./scripts/linux/clear-cache.sh"
echo "    🪟 scripts\\windows\\clear-cache.bat"
echo ""
echo "  ⚠️  This clears ALL cache:"
echo "     - Bulk job cache (all_jobs)"
echo "     - Query-specific caches"
echo "     - Recommended jobs cache"
echo ""
echo "  Use when:"
echo "     - Testing with fresh data"
echo "     - Jobs should reload from database"
echo "     - Debugging cache issues"
echo ""
echo ""

echo "📊 CHECK REDIS STATUS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Prerequisites: redis-cli installed (brew install redis)"
echo ""
echo "  List all keys:"
echo "    redis-cli -u \$REDIS_URL KEYS '*'"
echo ""
echo "  Count keys:"
echo "    redis-cli -u \$REDIS_URL DBSIZE"
echo ""
echo "  See specific key:"
echo "    redis-cli -u \$REDIS_URL GET all_jobs"
echo ""
echo "  Monitor in real-time:"
echo "    redis-cli -u \$REDIS_URL MONITOR"
echo ""
echo "  Note: \$REDIS_URL is loaded from .env.local"
echo ""
echo ""

echo "🔍 VIEW LOGS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Backend logs (shows cache operations):"
echo "    docker-compose logs -f backend"
echo ""
echo "    Look for: [CACHE HIT], [CACHE MISS], [CACHE SET]"
echo ""
echo "  Upstash Web Console:"
echo "    https://console.upstash.io"
echo "    Login with your Upstash credentials to view metrics"
echo ""
echo ""

echo "📋 REDIS CONNECTION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Connection string (from .env.local):"
echo "    REDIS_URL=rediss://default:<token>@<host>:6379"
echo ""
echo "  Redis CLI (interactive with Upstash):"
echo "    redis-cli -u \"\$REDIS_URL\""
echo ""
echo "    (First, load from .env.local:)"
echo "    source .env.local && redis-cli -u \"\$REDIS_URL\""
echo ""
echo ""

echo "⚙️  CONFIGURATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Environment variables (.env.local):"
echo "    REDIS_URL - Main connection string (TCP/TLS)"
echo "    UPSTASH_REDIS_REST_URL - REST API URL (optional)"
echo "    UPSTASH_REDIS_REST_TOKEN - REST API token (optional)"
echo ""
echo "  No changes needed to docker-compose.yml"
echo "  Redis is automatically used by the backend"
echo ""
echo ""

echo "  For detailed documentation, see: scripts/README.md"
echo ""
