"use client";

import { useState } from "react";
import { Lock, User2, Eye, EyeOff, Shield, Loader2, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiFetch } from "@/lib/api-client";
import { useAuth } from "@/context/AuthContext";

export default function ChangePasswordPage() {
  const { user, logout } = useAuth();
  const [isLoading, setIsLoading] = useState(false);
  const [showCurrentPw, setShowCurrentPw] = useState(false);
  const [showNewPw, setShowNewPw] = useState(false);
  const [showConfirmPw, setShowConfirmPw] = useState(false);
  const [done, setDone] = useState(false);

  const [form, setForm] = useState({
    newUsername: "",
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user?.user_id) {
      toast.error("You must be logged in to change your credentials.");
      return;
    }
    if (form.newPassword !== form.confirmPassword) {
      toast.error("New passwords do not match.");
      return;
    }
    if (form.newPassword.length < 8) {
      toast.error("New password must be at least 8 characters.");
      return;
    }
    setIsLoading(true);
    try {
      await apiFetch(`/users/${user.user_id}`, {
        method: "PATCH",
        body: {
          username: form.newUsername || undefined,
          current_password: form.currentPassword,
          password: form.newPassword,
        },
      });
      toast.success("Credentials updated! Please log in with your new credentials.");
      setDone(true);
      setTimeout(() => {
        logout();
      }, 2000);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Failed to update credentials.";
      toast.error(msg);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
      <div className="w-full max-w-md">
        {/* Card */}
        <div className="bg-white rounded-2xl shadow-xl shadow-slate-200/60 border border-slate-100 overflow-hidden">
          {/* Header gradient strip */}
          <div className="h-2 bg-gradient-to-r from-emerald-600 to-teal-500" />

          <div className="p-8">
            {/* Icon + Title */}
            <div className="flex flex-col items-center text-center gap-3 mb-8">
              <div className="w-14 h-14 rounded-2xl bg-emerald-100 flex items-center justify-center shadow-sm">
                <Shield className="w-7 h-7 text-emerald-600" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-slate-900">First Login — Change Credentials</h1>
                <p className="text-sm text-slate-500 mt-1 leading-relaxed">
                  Your account was auto-generated by the registrar. Please set a new username and password to secure your account.
                </p>
              </div>
            </div>

            {done ? (
              <div className="flex flex-col items-center gap-3 py-8 text-center animate-in fade-in">
                <CheckCircle2 className="w-12 h-12 text-emerald-600" />
                <p className="font-bold text-slate-800">Credentials updated!</p>
                <p className="text-sm text-slate-500">Redirecting to login…</p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4">
                {/* New Username */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-600 uppercase tracking-wide">
                    New Username <span className="text-emerald-600">(optional)</span>
                  </label>
                  <div className="relative">
                    <User2 className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                    <Input
                      type="text"
                      placeholder="Choose a username (leave blank to keep current)"
                      className="pl-10 rounded-xl border-slate-200"
                      value={form.newUsername}
                      onChange={(e) => setForm((f) => ({ ...f, newUsername: e.target.value }))}
                    />
                  </div>
                </div>

                {/* Current Password */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-600 uppercase tracking-wide">
                    Current (Temporary) Password <span className="text-red-500">*</span>
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                    <Input
                      type={showCurrentPw ? "text" : "password"}
                      placeholder="Enter the password from your email"
                      className="pl-10 pr-10 rounded-xl border-slate-200"
                      value={form.currentPassword}
                      onChange={(e) => setForm((f) => ({ ...f, currentPassword: e.target.value }))}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowCurrentPw((v) => !v)}
                      className="absolute inset-y-0 right-3.5 flex items-center text-slate-400 hover:text-slate-600"
                    >
                      {showCurrentPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                {/* New Password */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-600 uppercase tracking-wide">
                    New Password <span className="text-red-500">*</span>
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                    <Input
                      type={showNewPw ? "text" : "password"}
                      placeholder="Min. 8 chars, uppercase + number + special"
                      className="pl-10 pr-10 rounded-xl border-slate-200"
                      value={form.newPassword}
                      onChange={(e) => setForm((f) => ({ ...f, newPassword: e.target.value }))}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowNewPw((v) => !v)}
                      className="absolute inset-y-0 right-3.5 flex items-center text-slate-400 hover:text-slate-600"
                    >
                      {showNewPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                {/* Confirm New Password */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-600 uppercase tracking-wide">
                    Confirm New Password <span className="text-red-500">*</span>
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                    <Input
                      type={showConfirmPw ? "text" : "password"}
                      placeholder="Repeat your new password"
                      className="pl-10 pr-10 rounded-xl border-slate-200"
                      value={form.confirmPassword}
                      onChange={(e) => setForm((f) => ({ ...f, confirmPassword: e.target.value }))}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowConfirmPw((v) => !v)}
                      className="absolute inset-y-0 right-3.5 flex items-center text-slate-400 hover:text-slate-600"
                    >
                      {showConfirmPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                <Button
                  type="submit"
                  disabled={isLoading}
                  className="w-full h-11 mt-2 rounded-xl font-semibold bg-gradient-to-r from-emerald-700 to-emerald-600 hover:from-emerald-700 hover:to-emerald-700 text-white shadow-lg shadow-emerald-700/25 transition-all"
                >
                  {isLoading ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                  ) : (
                    "Update Credentials"
                  )}
                </Button>
              </form>
            )}
          </div>
        </div>

        <p className="text-center text-xs text-slate-400 mt-6">
          Need help? Contact your department registrar.
        </p>
      </div>
    </div>
  );
}
