"""added placement tracking fields to alumni

Revision ID: 0de80df56141
Revises: f65499196f0a
Create Date: 2026-03-26 23:03:50.682047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0de80df56141'
down_revision: Union[str, Sequence[str], None] = 'f65499196f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('employment_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('alumni', sa.Column('employment_sector', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('alumni', sa.Column('salary_package', sa.Float(), nullable=True))
    op.add_column('alumni', sa.Column('offers_received', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni', 'offers_received')
    op.drop_column('alumni', 'salary_package')
    op.drop_column('alumni', 'employment_sector')
    op.drop_column('alumni', 'employment_status')
    # ### end Alembic commands ###
