"""added_staff_table

Revision ID: 1d111cc3cdc9
Revises: a3c0b3c822ee
Create Date: 2026-03-24 23:08:30.840463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d111cc3cdc9'
down_revision: Union[str, Sequence[str], None] = 'a3c0b3c822ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('staff_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('staff_code', sa.Uuid(), nullable=False),
    sa.Column('user_code', sa.Uuid(), nullable=True),
    sa.Column('college_dept_code', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_dept_code'], ['college_depts.college_dept_code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('staff_code')
    )
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
