"""added survey target columns

Revision ID: 2659cb436bd9
Revises: 4046144b69c2
Create Date: 2026-05-09 20:04:13.224025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2659cb436bd9'
down_revision: Union[str, Sequence[str], None] = '4046144b69c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('target_department_abbv', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('surveys', sa.Column('target_course_abbv', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'target_course_abbv')
    op.drop_column('surveys', 'target_department_abbv')
    # ### end Alembic commands ###
