"""Add Employer profile table

Revision ID: 28f2409aa5c1
Revises: a1b2c3d4e5f6
Create Date: 2026-04-23 00:41:03.276044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28f2409aa5c1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('user_code', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_person_first_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('contact_person_last_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('contact_person_position', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('employer_id')
    )
    op.create_index(op.f('ix_employers_user_code'), 'employers', ['user_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employers_user_code'), table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###
