"""Add alumni_resumes table

Revision ID: 3713ea26f4f3
Revises: c351878bea49
Create Date: 2026-04-24 22:15:27.652799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3713ea26f4f3'
down_revision: Union[str, Sequence[str], None] = 'c351878bea49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_resumes',
    sa.Column('resume_code', sa.Uuid(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=False),
    sa.Column('resume_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_code')
    )
    op.create_index(op.f('ix_alumni_resumes_alumni_code'), 'alumni_resumes', ['alumni_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumni_resumes_alumni_code'), table_name='alumni_resumes')
    op.drop_table('alumni_resumes')
    # ### end Alembic commands ###
