"""refactored consert for survey ml from student records to alumni, added birthdate as well

Revision ID: 42d159a01027
Revises: d49c6c0b7f5a
Create Date: 2026-02-27 18:17:56.065762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42d159a01027'
down_revision: Union[str, Sequence[str], None] = 'd49c6c0b7f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('alumni', sa.Column('consent_for_survey_ml', sa.Boolean(), nullable=False))
    op.drop_column('student_records', 'consent_for_survey_ml')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_records', sa.Column('consent_for_survey_ml', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('alumni', 'consent_for_survey_ml')
    op.drop_column('alumni', 'birthdate')
    # ### end Alembic commands ###
