"""Add skills to Alumni

Revision ID: 56051b3c68d7
Revises: 7c7f67b2b740
Create Date: 2026-04-27 01:47:39.082987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56051b3c68d7'
down_revision: Union[str, Sequence[str], None] = '7c7f67b2b740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('skills', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni', 'skills')
    # ### end Alembic commands ###
