"""add company_logo_public_id to employers

Revision ID: 6595f95a46ac
Revises: cbfc8a957ce5
Create Date: 2026-04-24 18:13:56.851683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6595f95a46ac'
down_revision: Union[str, Sequence[str], None] = 'cbfc8a957ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('company_logo_public_id', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'company_logo_public_id')
    # ### end Alembic commands ###
