"""increased length for user id

Revision ID: 7111eb9e2e33
Revises: 1d111cc3cdc9
Create Date: 2026-03-24 23:41:25.211713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7111eb9e2e33'
down_revision: Union[str, Sequence[str], None] = '1d111cc3cdc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'staff_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'staff_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
