"""added event type tables

Revision ID: 88f4a75d8c7a
Revises: 42d159a01027
Create Date: 2026-03-03 19:03:54.631823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88f4a75d8c7a'
down_revision: Union[str, Sequence[str], None] = '42d159a01027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('event_type_code', sa.Uuid(), nullable=False),
    sa.Column('event_type_id', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_type_code')
    )
    op.create_index(op.f('ix_event_types_event_name'), 'event_types', ['event_name'], unique=True)
    op.create_index(op.f('ix_event_types_event_type_id'), 'event_types', ['event_type_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_types_event_type_id'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_event_name'), table_name='event_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
