"""add_ml_tables_and_student_record_columns

Revision ID: 9522883d1b6b
Revises: 9538f0373786
Create Date: 2026-04-10 14:13:34.253717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9522883d1b6b'
down_revision: Union[str, Sequence[str], None] = '9538f0373786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_regression_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('prediction_result', sa.JSON(), nullable=False),
    sa.Column('predicted_salary', sa.Float(), nullable=False),
    sa.Column('predicted_duration_weeks', sa.Float(), nullable=False),
    sa.Column('salary_band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('search_outlook', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arima_forecast_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=False),
    sa.Column('data_source', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('observations_count', sa.Integer(), nullable=False),
    sa.Column('forecast_steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student_records', sa.Column('projects', sa.Integer(), nullable=True))
    op.add_column('student_records', sa.Column('extracurricular', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_records', 'extracurricular')
    op.drop_column('student_records', 'projects')
    op.drop_table('arima_forecast_results')
    op.drop_table('alumni_regression_predictions')
    # ### end Alembic commands ###
