"""Drop survey distribution and invitation tables

Revision ID: 9538f0373786
Revises: e3cd7b237040
Create Date: 2026-04-05 14:08:27.048096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9538f0373786'
down_revision: Union[str, Sequence[str], None] = 'e3cd7b237040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_distribution_configs_distribution_id'), table_name='survey_distribution_configs')
    op.drop_table('survey_distribution_configs')
    op.drop_index(op.f('ix_survey_invitations_invitation_id'), table_name='survey_invitations')
    op.drop_table('survey_invitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_invitations',
    sa.Column('survey_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alumni_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'OPENED', 'RESPONDED', 'EXPIRED', name='surveyinvitationstatus'), autoincrement=False, nullable=False),
    sa.Column('invitation_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invitation_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], name=op.f('survey_invitations_alumni_code_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_code'], ['surveys.survey_code'], name=op.f('survey_invitations_survey_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_code', name=op.f('survey_invitations_pkey'))
    )
    op.create_index(op.f('ix_survey_invitations_invitation_id'), 'survey_invitations', ['invitation_id'], unique=True)
    op.create_table('survey_distribution_configs',
    sa.Column('survey_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_group', postgresql.ENUM('ALL_ALUMNI', 'SPECIFIC_COURSE', 'GRADUATION_YEAR_RANGE', 'CUSTOM_LIST', name='distributiontargetgroup'), autoincrement=False, nullable=False),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SCHEDULED', 'SENT', 'COMPLETED', name='distributionstatus'), autoincrement=False, nullable=False),
    sa.Column('total_recipients', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_send_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('distribution_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('distribution_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_code'], ['surveys.survey_code'], name=op.f('survey_distribution_configs_survey_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('distribution_code', name=op.f('survey_distribution_configs_pkey')),
    sa.UniqueConstraint('survey_code', name=op.f('uq_survey_distribution_configs_survey_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_survey_distribution_configs_distribution_id'), 'survey_distribution_configs', ['distribution_id'], unique=True)
    # ### end Alembic commands ###
