"""add user activity table

Revision ID: a3c0b3c822ee
Revises: 311e7e90fd7b
Create Date: 2026-03-24 20:52:23.900490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3c0b3c822ee'
down_revision: Union[str, Sequence[str], None] = '311e7e90fd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('activity_code', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('user_code', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.Enum('LOGIN', 'LOGOUT', 'REGISTER_FOR_EVENT', 'UNREGISTER_FROM_EVENT', 'SUBMIT_SURVEY', 'UPDATE_PROFILE', 'PASSWORD_RESET', name='activitytype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('activity_code')
    )
    op.create_index(op.f('ix_user_activities_activity_id'), 'user_activities', ['activity_id'], unique=True)
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_user_code'), 'user_activities', ['user_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_user_code'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_id'), table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
