"""creatd schema for survey

Revision ID: bcbade85b6ef
Revises: b7399878250c
Create Date: 2026-02-22 13:24:16.817971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcbade85b6ef'
down_revision: Union[str, Sequence[str], None] = 'b7399878250c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'MULTI_SELECT', 'TEXT', 'SCALE', 'YES_NO', 'DATE', 'NUMBER', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('scale_label_min', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('scale_label_max', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('placeholder', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('question_code', sa.Uuid(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('question_code')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=True)
    op.create_table('surveys',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple_responses', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('survey_code', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED', name='surveystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('survey_code')
    )
    op.create_index(op.f('ix_surveys_survey_id'), 'surveys', ['survey_id'], unique=True)
    op.create_table('survey_distribution_configs',
    sa.Column('survey_code', sa.Uuid(), nullable=False),
    sa.Column('target_group', sa.Enum('ALL_ALUMNI', 'SPECIFIC_COURSE', 'GRADUATION_YEAR_RANGE', 'CUSTOM_LIST', name='distributiontargetgroup'), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENT', 'COMPLETED', name='distributionstatus'), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('scheduled_send_at', sa.DateTime(), nullable=True),
    sa.Column('distribution_code', sa.Uuid(), nullable=False),
    sa.Column('distribution_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_code'], ['surveys.survey_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('distribution_code'),
    sa.UniqueConstraint('survey_code', name='uq_survey_distribution_configs_survey_code')
    )
    op.create_index(op.f('ix_survey_distribution_configs_distribution_id'), 'survey_distribution_configs', ['distribution_id'], unique=True)
    op.create_table('survey_invitations',
    sa.Column('survey_code', sa.Uuid(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=False),
    sa.Column('recipient_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'OPENED', 'RESPONDED', 'EXPIRED', name='surveyinvitationstatus'), nullable=False),
    sa.Column('invitation_code', sa.Uuid(), nullable=False),
    sa.Column('invitation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_code'], ['surveys.survey_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_code')
    )
    op.create_index(op.f('ix_survey_invitations_invitation_id'), 'survey_invitations', ['invitation_id'], unique=True)
    op.create_table('survey_questions',
    sa.Column('survey_code', sa.Uuid(), nullable=False),
    sa.Column('question_code', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('survey_question_code', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_code'], ['questions.question_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_code'], ['surveys.survey_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_question_code'),
    sa.UniqueConstraint('survey_code', 'order_index', name='uq_survey_questions_survey_code_order_index'),
    sa.UniqueConstraint('survey_code', 'question_code', name='uq_survey_questions_survey_code_question_code')
    )
    op.create_table('survey_responses',
    sa.Column('survey_code', sa.Uuid(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=True),
    sa.Column('response_code', sa.Uuid(), nullable=False),
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_code'], ['surveys.survey_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_code')
    )
    op.create_index(op.f('ix_survey_responses_response_id'), 'survey_responses', ['response_id'], unique=True)
    op.create_table('survey_answers',
    sa.Column('response_code', sa.Uuid(), nullable=False),
    sa.Column('question_code', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('answer_choice', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('answer_choices', sa.JSON(), nullable=True),
    sa.Column('answer_scale', sa.Integer(), nullable=True),
    sa.Column('answer_number', sa.Float(), nullable=True),
    sa.Column('answer_date', sa.DateTime(), nullable=True),
    sa.Column('answer_bool', sa.Boolean(), nullable=True),
    sa.Column('answer_code', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_code'], ['questions.question_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_code'], ['survey_responses.response_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_code')
    )
    op.add_column('event_registrations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('event_registrations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('student_records', sa.Column('consent_for_survey_ml', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_records', 'consent_for_survey_ml')
    op.drop_column('event_registrations', 'deleted_at')
    op.drop_column('event_registrations', 'is_deleted')
    op.drop_table('survey_answers')
    op.drop_index(op.f('ix_survey_responses_response_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_survey_invitations_invitation_id'), table_name='survey_invitations')
    op.drop_table('survey_invitations')
    op.drop_index(op.f('ix_survey_distribution_configs_distribution_id'), table_name='survey_distribution_configs')
    op.drop_table('survey_distribution_configs')
    op.drop_index(op.f('ix_surveys_survey_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
