"""add schedule to job application

Revision ID: bdaecac698e8
Revises: b5f6e0bc34ce
Create Date: 2026-04-27 23:54:46.055531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdaecac698e8'
down_revision: Union[str, Sequence[str], None] = 'b5f6e0bc34ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_alumni_id_tmp'), 'alumni', type_='unique')
    op.drop_constraint(op.f('uq_alumni_resumes_id_tmp'), 'alumni_resumes', type_='unique')
    op.drop_index(op.f('ix_alumni_resumes_alumni_ref_id'), table_name='alumni_resumes')
    op.create_index(op.f('ix_alumni_resumes_alumni_ref_id'), 'alumni_resumes', ['alumni_ref_id'], unique=True)
    op.drop_constraint(op.f('uq_alumni_skills_id_tmp'), 'alumni_skills', type_='unique')
    op.create_unique_constraint(None, 'alumni_skills', ['alumni_ref_id'])
    op.drop_constraint(op.f('uq_college_depts_id_tmp'), 'college_depts', type_='unique')
    op.drop_constraint(op.f('uq_courses_id_tmp'), 'courses', type_='unique')
    op.drop_constraint(op.f('uq_employers_id_tmp'), 'employers', type_='unique')
    op.drop_constraint(op.f('uq_employers_user_ref_id'), 'employers', type_='unique')
    op.create_index(op.f('ix_employers_user_ref_id'), 'employers', ['user_ref_id'], unique=True)
    op.drop_constraint(op.f('uq_event_registrations_id_tmp'), 'event_registrations', type_='unique')
    op.drop_constraint(op.f('uq_event_types_id_tmp'), 'event_types', type_='unique')
    op.drop_constraint(op.f('uq_events_id_tmp'), 'events', type_='unique')
    op.add_column('job_applications', sa.Column('interview_date', sa.DateTime(), nullable=True))
    op.add_column('job_applications', sa.Column('interview_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('uq_mentoring_sessions_id_tmp'), 'mentoring_sessions', type_='unique')
    op.drop_constraint(op.f('uq_questions_id_tmp'), 'questions', type_='unique')
    op.drop_constraint(op.f('uq_skills_id_tmp'), 'skills', type_='unique')
    op.drop_constraint(op.f('uq_skills_list_id_tmp'), 'skills_list', type_='unique')
    op.drop_constraint(op.f('uq_staff_id_tmp'), 'staff', type_='unique')
    op.drop_constraint(op.f('uq_student_records_id_tmp'), 'student_records', type_='unique')
    op.drop_constraint(op.f('uq_survey_questions_id_tmp'), 'survey_questions', type_='unique')
    op.drop_constraint(op.f('uq_survey_responses_id_tmp'), 'survey_responses', type_='unique')
    op.drop_constraint(op.f('uq_surveys_id_tmp'), 'surveys', type_='unique')
    op.drop_constraint(op.f('uq_transaction_logs_id_tmp'), 'transaction_logs', type_='unique')
    op.drop_constraint(op.f('uq_user_activities_id_tmp'), 'user_activities', type_='unique')
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_activities_id_tmp'), 'user_activities', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_transaction_logs_id_tmp'), 'transaction_logs', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_surveys_id_tmp'), 'surveys', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_survey_responses_id_tmp'), 'survey_responses', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_survey_questions_id_tmp'), 'survey_questions', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_student_records_id_tmp'), 'student_records', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_staff_id_tmp'), 'staff', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_skills_list_id_tmp'), 'skills_list', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_skills_id_tmp'), 'skills', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_questions_id_tmp'), 'questions', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_mentoring_sessions_id_tmp'), 'mentoring_sessions', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_column('job_applications', 'interview_link')
    op.drop_column('job_applications', 'interview_date')
    op.create_unique_constraint(op.f('uq_events_id_tmp'), 'events', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_event_types_id_tmp'), 'event_types', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_event_registrations_id_tmp'), 'event_registrations', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_employers_user_ref_id'), table_name='employers')
    op.create_unique_constraint(op.f('uq_employers_user_ref_id'), 'employers', ['user_ref_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_employers_id_tmp'), 'employers', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_courses_id_tmp'), 'courses', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_college_depts_id_tmp'), 'college_depts', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'alumni_skills', type_='unique')
    op.create_unique_constraint(op.f('uq_alumni_skills_id_tmp'), 'alumni_skills', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_alumni_resumes_alumni_ref_id'), table_name='alumni_resumes')
    op.create_index(op.f('ix_alumni_resumes_alumni_ref_id'), 'alumni_resumes', ['alumni_ref_id'], unique=False)
    op.create_unique_constraint(op.f('uq_alumni_resumes_id_tmp'), 'alumni_resumes', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_alumni_id_tmp'), 'alumni', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
