"""Add company_logo_url

Revision ID: cbfc8a957ce5
Revises: f57aa12c451b
Create Date: 2026-04-24 17:17:08.836354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbfc8a957ce5'
down_revision: Union[str, Sequence[str], None] = 'f57aa12c451b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('company_logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'company_logo_url')
    # ### end Alembic commands ###
