"""added alumni_skills table

Revision ID: d49c6c0b7f5a
Revises: e45c87c3cd41
Create Date: 2026-02-27 17:32:43.487831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd49c6c0b7f5a'
down_revision: Union[str, Sequence[str], None] = 'e45c87c3cd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_skills',
    sa.Column('skill_code', sa.Uuid(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=False),
    sa.Column('soft_skills_ave', sa.Float(), nullable=True),
    sa.Column('hard_skills_ave', sa.Float(), nullable=True),
    sa.Column('program_skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_code'),
    sa.UniqueConstraint('alumni_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumni_skills')
    # ### end Alembic commands ###
