"""Refactor survey answers to json

Revision ID: e3cd7b237040
Revises: 0de80df56141
Create Date: 2026-04-05 13:49:29.787222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3cd7b237040'
down_revision: Union[str, Sequence[str], None] = '0de80df56141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_answers')
    op.add_column('survey_responses', sa.Column('answers', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'answers')
    op.create_table('survey_answers',
    sa.Column('response_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('answer_choice', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('answer_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('answer_scale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('answer_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('answer_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('answer_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_code'], ['questions.question_code'], name=op.f('survey_answers_question_code_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_code'], ['survey_responses.response_code'], name=op.f('survey_answers_response_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_code', name=op.f('survey_answers_pkey'))
    )
    # ### end Alembic commands ###
