"""add company contact number to employers

Revision ID: f57aa12c451b
Revises: 959eaf6822fb
Create Date: 2026-04-24 15:28:41.070489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f57aa12c451b'
down_revision: Union[str, Sequence[str], None] = '959eaf6822fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('company_contact_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'company_contact_number')
    # ### end Alembic commands ###
