"""added mentoring table

Revision ID: f65499196f0a
Revises: 7111eb9e2e33
Create Date: 2026-03-26 22:47:05.660169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f65499196f0a'
down_revision: Union[str, Sequence[str], None] = '7111eb9e2e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentoring_sessions',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('session_code', sa.Uuid(), nullable=False),
    sa.Column('faculty_user_code', sa.Uuid(), nullable=False),
    sa.Column('alumni_user_code', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_user_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['faculty_user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('session_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentoring_sessions')
    # ### end Alembic commands ###
