from enum import Enum
from pydantic import BaseModel, Field, field_serializer
from typing import Optional, Any
from datetime import datetime
from utils.timezone import format_datetime_gmt8, get_current_time_gmt8

# Response codes for API endpoints


class ErrorCode(str, Enum):
    """Error codes for API responses"""

    # Duplicate/Conflict errors
    DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
    DUPLICATE_USERNAME = "DUPLICATE_USERNAME"
    DUPLICATE_STUDENT_ID = "DUPLICATE_STUDENT_ID"
    DUPLICATE_ALUMNI_ID = "DUPLICATE_ALUMNI_ID"
    DUPLICATE_DEGREE_ID = "DUPLICATE_DEGREE_ID"  # Legacy - use DUPLICATE_COURSE_ID
    DUPLICATE_COURSE_ID = "DUPLICATE_COURSE_ID"
    DUPLICATE_COURSE_ABBV = "DUPLICATE_COURSE_ABBV"
    DUPLICATE_COURSE_NAME = "DUPLICATE_COURSE_NAME"
    DUPLICATE_COLLEGE_DEPT_ID = "DUPLICATE_COLLEGE_DEPT_ID"
    DUPLICATE_COLLEGE_DEPT_ABBV = "DUPLICATE_COLLEGE_DEPT_ABBV"
    DUPLICATE_COLLEGE_DEPT_NAME = "DUPLICATE_COLLEGE_DEPT_NAME"
    ALUMNI_ALREADY_HAS_STUDENT_RECORD = "ALUMNI_ALREADY_HAS_STUDENT_RECORD"

    # Not found errors
    DEGREE_NOT_FOUND = "DEGREE_NOT_FOUND"  # Legacy - use COURSE_NOT_FOUND
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
    COLLEGE_DEPT_NOT_FOUND = "COLLEGE_DEPT_NOT_FOUND"
    ALUMNI_NOT_FOUND = "ALUMNI_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    STUDENT_RECORD_NOT_FOUND = "STUDENT_RECORD_NOT_FOUND"
    ALUMNI_SKILLS_NOT_FOUND = "ALUMNI_SKILLS_NOT_FOUND"
    ALUMNI_ALREADY_HAS_SKILLS_RECORD = "ALUMNI_ALREADY_HAS_SKILLS_RECORD"

    # Authentication/Authorization errors
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    FORBIDDEN = "FORBIDDEN"
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
    MISSING_CURRENT_PASSWORD = "MISSING_CURRENT_PASSWORD"

    # Validation errors
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    INVALID_YEAR_GRADUATED = "INVALID_YEAR_GRADUATED"
    INVALID_AGE = "INVALID_AGE"

    # Soft delete errors
    ALREADY_DELETED = "ALREADY_DELETED"
    CANNOT_DELETE_USER_WITH_ACTIVE_ALUMNI = "CANNOT_DELETE_USER_WITH_ACTIVE_ALUMNI"
    CANNOT_DELETE_ALUMNI_WITH_ACTIVE_STUDENT_RECORDS = (
        "CANNOT_DELETE_ALUMNI_WITH_ACTIVE_STUDENT_RECORDS"
    )
    CANNOT_DELETE_COURSE_WITH_ACTIVE_STUDENT_RECORDS = (
        "CANNOT_DELETE_COURSE_WITH_ACTIVE_STUDENT_RECORDS"
    )
    CANNOT_DELETE_COLLEGE_DEPT_WITH_ACTIVE_COURSES = (
        "CANNOT_DELETE_COLLEGE_DEPT_WITH_ACTIVE_COURSES"
    )

    # Event errors
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_ALREADY_DELETED = "EVENT_ALREADY_DELETED"
    EVENT_NOT_DELETED = "EVENT_NOT_DELETED"
    DUPLICATE_EVENT_ID = "DUPLICATE_EVENT_ID"
    EVENT_CAPACITY_FULL = "EVENT_CAPACITY_FULL"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"
    REGISTRATION_NOT_FOUND = "REGISTRATION_NOT_FOUND"

    # Event Type errors
    EVENT_TYPE_NOT_FOUND = "EVENT_TYPE_NOT_FOUND"
    EVENT_TYPE_NOT_DELETED = "EVENT_TYPE_NOT_DELETED"
    DUPLICATE_EVENT_TYPE_NAME = "DUPLICATE_EVENT_TYPE_NAME"
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    IMAGE_UPLOAD_FAILED = "IMAGE_UPLOAD_FAILED"
    IMAGE_DELETE_FAILED = "IMAGE_DELETE_FAILED"
    IMAGE_URL_FAILED = "IMAGE_URL_FAILED"
    IMAGE_INVALID_TYPE = "IMAGE_INVALID_TYPE"
    IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"

    # Survey/Question errors
    QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"
    DUPLICATE_QUESTION_ID = "DUPLICATE_QUESTION_ID"
    DUPLICATE_QUESTION_TEXT = "DUPLICATE_QUESTION_TEXT"
    SURVEY_NOT_FOUND = "SURVEY_NOT_FOUND"
    DUPLICATE_SURVEY_ID = "DUPLICATE_SURVEY_ID"
    DUPLICATE_SURVEY_TITLE = "DUPLICATE_SURVEY_TITLE"
    SURVEY_NOT_ACTIVE = "SURVEY_NOT_ACTIVE"
    SURVEY_ALREADY_CLOSED = "SURVEY_ALREADY_CLOSED"
    SURVEY_NOT_DRAFT = "SURVEY_NOT_DRAFT"
    SURVEY_HAS_NO_QUESTIONS = "SURVEY_HAS_NO_QUESTIONS"
    SURVEY_QUESTION_NOT_FOUND = "SURVEY_QUESTION_NOT_FOUND"
    DUPLICATE_RESPONSE = "DUPLICATE_RESPONSE"
    INCOMPLETE_RESPONSE = "INCOMPLETE_RESPONSE"
    INVALID_ANSWER_TYPE = "INVALID_ANSWER_TYPE"
    DISTRIBUTION_CONFIG_NOT_FOUND = "DISTRIBUTION_CONFIG_NOT_FOUND"
    DISTRIBUTION_ALREADY_SENT = "DISTRIBUTION_ALREADY_SENT"
    INVALID_TARGET_GROUP_FILTERS = "INVALID_TARGET_GROUP_FILTERS"
    NO_RECIPIENTS_FOUND = "NO_RECIPIENTS_FOUND"
    DISTRIBUTION_NOT_DRAFT = "DISTRIBUTION_NOT_DRAFT"

    # Prediction errors
    PREDICTION_FAILED = "PREDICTION_FAILED"
    PREDICTION_NOT_FOUND = "PREDICTION_NOT_FOUND"
    INVALID_DEGREE = "INVALID_DEGREE"
    MODEL_NOT_LOADED = "MODEL_NOT_LOADED"

    # Regression prediction errors
    REGRESSION_PREDICTION_FAILED = "REGRESSION_PREDICTION_FAILED"
    REGRESSION_PREDICTION_NOT_FOUND = "REGRESSION_PREDICTION_NOT_FOUND"
    REGRESSION_MISSING_DATA = "REGRESSION_MISSING_DATA"

    # ARIMA forecast errors
    FORECAST_FAILED = "FORECAST_FAILED"
    FORECAST_NOT_FOUND = "FORECAST_NOT_FOUND"

    # Alumni data errors
    STUDENT_RECORD_NOT_LINKED = "STUDENT_RECORD_NOT_LINKED"
    ALUMNI_SKILLS_NOT_LINKED = "ALUMNI_SKILLS_NOT_LINKED"

    # Generic errors
    REGISTRATION_FAILED = "REGISTRATION_FAILED"

    # OTP errors
    OTP_SEND_FAILED = "OTP_SEND_FAILED"
    OTP_EXPIRED = "OTP_EXPIRED"
    OTP_INVALID = "OTP_INVALID"
    OTP_MAX_ATTEMPTS_EXCEEDED = "OTP_MAX_ATTEMPTS_EXCEEDED"
    OTP_RATE_LIMIT_EXCEEDED = "OTP_RATE_LIMIT_EXCEEDED"
    REDIS_UNAVAILABLE = "REDIS_UNAVAILABLE"

    # Server/Internal errors
    SERVER_ERROR_INTERNAL = "SERVER_ERROR_INTERNAL"
    UNIQUE_CONSTRAINT_VIOLATION = "UNIQUE_CONSTRAINT_VIOLATION"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    DUPLICATE_USER_ID = "DUPLICATE_USER_ID"


class SuccessCode(str, Enum):
    """Success codes for API responses"""

    SUCCESS = "SUCCESS"

    # User operations
    USER_CREATED = "USER_CREATED"
    USER_RETRIEVED = "USER_RETRIEVED"
    USERS_RETRIEVED = "USERS_RETRIEVED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_RESTORED = "USER_RESTORED"
    USERS_BATCH_CREATED = "USERS_BATCH_CREATED"
    USERS_BATCH_UPDATED = "USERS_BATCH_UPDATED"
    USERS_BATCH_DELETED = "USERS_BATCH_DELETED"
    USERS_BATCH_RESTORED = "USERS_BATCH_RESTORED"

    # Alumni operations
    ALUMNI_CREATED = "ALUMNI_CREATED"
    ALUMNI_RETRIEVED = "ALUMNI_RETRIEVED"
    ALUMNI_LIST_RETRIEVED = "ALUMNI_LIST_RETRIEVED"
    ALUMNI_UPDATED = "ALUMNI_UPDATED"
    ALUMNI_DELETED = "ALUMNI_DELETED"
    ALUMNI_RESTORED = "ALUMNI_RESTORED"
    ALUMNI_BATCH_REGISTERED = "ALUMNI_BATCH_REGISTERED"
    ALUMNI_BATCH_UPDATED = "ALUMNI_BATCH_UPDATED"
    ALUMNI_BATCH_DELETED = "ALUMNI_BATCH_DELETED"
    ALUMNI_BATCH_RESTORED = "ALUMNI_BATCH_RESTORED"
    ALUMNI_ACTIVITY_RETRIEVED = "ALUMNI_ACTIVITY_RETRIEVED"
    EMPLOYER_ACTIVITY_RETRIEVED = "EMPLOYER_ACTIVITY_RETRIEVED"

    # Alumni skills operations
    ALUMNI_SKILLS_CREATED = "ALUMNI_SKILLS_CREATED"
    ALUMNI_SKILLS_RETRIEVED = "ALUMNI_SKILLS_RETRIEVED"
    ALUMNI_SKILLS_UPDATED = "ALUMNI_SKILLS_UPDATED"
    ALUMNI_SKILLS_DELETED = "ALUMNI_SKILLS_DELETED"
    ALUMNI_SKILLS_BATCH_CREATED = "ALUMNI_SKILLS_BATCH_CREATED"
    ALUMNI_SKILLS_BATCH_UPDATED = "ALUMNI_SKILLS_BATCH_UPDATED"

    # Student record operations
    STUDENT_RECORD_CREATED = "STUDENT_RECORD_CREATED"
    STUDENT_RECORD_RETRIEVED = "STUDENT_RECORD_RETRIEVED"
    STUDENT_RECORDS_RETRIEVED = "STUDENT_RECORDS_RETRIEVED"
    STUDENT_RECORD_UPDATED = "STUDENT_RECORD_UPDATED"
    STUDENT_RECORD_DELETED = "STUDENT_RECORD_DELETED"
    STUDENT_RECORD_RESTORED = "STUDENT_RECORD_RESTORED"
    STUDENT_RECORDS_BATCH_CREATED = "STUDENT_RECORDS_BATCH_CREATED"
    STUDENT_RECORDS_BATCH_UPDATED = "STUDENT_RECORDS_BATCH_UPDATED"
    STUDENT_RECORDS_BATCH_DELETED = "STUDENT_RECORDS_BATCH_DELETED"
    STUDENT_RECORDS_BATCH_RESTORED = "STUDENT_RECORDS_BATCH_RESTORED"

    # Degree operations (Legacy - use Course operations)
    DEGREE_CREATED = "DEGREE_CREATED"
    DEGREE_RETRIEVED = "DEGREE_RETRIEVED"
    DEGREES_RETRIEVED = "DEGREES_RETRIEVED"
    DEGREE_UPDATED = "DEGREE_UPDATED"
    DEGREE_DELETED = "DEGREE_DELETED"

    # College Department operations
    COLLEGE_DEPT_CREATED = "COLLEGE_DEPT_CREATED"
    COLLEGE_DEPT_RETRIEVED = "COLLEGE_DEPT_RETRIEVED"
    COLLEGE_DEPTS_RETRIEVED = "COLLEGE_DEPTS_RETRIEVED"
    COLLEGE_DEPT_UPDATED = "COLLEGE_DEPT_UPDATED"
    COLLEGE_DEPT_DELETED = "COLLEGE_DEPT_DELETED"
    COLLEGE_DEPT_RESTORED = "COLLEGE_DEPT_RESTORED"
    COLLEGE_DEPTS_BATCH_CREATED = "COLLEGE_DEPTS_BATCH_CREATED"
    COLLEGE_DEPTS_BATCH_UPDATED = "COLLEGE_DEPTS_BATCH_UPDATED"
    COLLEGE_DEPTS_BATCH_DELETED = "COLLEGE_DEPTS_BATCH_DELETED"
    COLLEGE_DEPTS_BATCH_RESTORED = "COLLEGE_DEPTS_BATCH_RESTORED"

    # Course operations
    COURSE_CREATED = "COURSE_CREATED"
    COURSE_RETRIEVED = "COURSE_RETRIEVED"
    COURSES_RETRIEVED = "COURSES_RETRIEVED"
    COURSE_UPDATED = "COURSE_UPDATED"
    COURSE_DELETED = "COURSE_DELETED"
    COURSE_RESTORED = "COURSE_RESTORED"
    COURSES_BATCH_CREATED = "COURSES_BATCH_CREATED"
    COURSES_BATCH_UPDATED = "COURSES_BATCH_UPDATED"
    COURSES_BATCH_DELETED = "COURSES_BATCH_DELETED"
    COURSES_BATCH_RESTORED = "COURSES_BATCH_RESTORED"

    # Event operations
    EVENT_CREATED = "EVENT_CREATED"
    EVENT_RETRIEVED = "EVENT_RETRIEVED"
    EVENTS_RETRIEVED = "EVENTS_RETRIEVED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_DELETED = "EVENT_DELETED"
    EVENT_RESTORED = "EVENT_RESTORED"
    EVENT_REGISTERED = "EVENT_REGISTERED"
    EVENT_UNREGISTERED = "EVENT_UNREGISTERED"

    # Job operations
    JOB_CREATED = "JOB_CREATED"
    JOB_RETRIEVED = "JOB_RETRIEVED"
    JOB_LIST_RETRIEVED = "JOB_LIST_RETRIEVED"
    JOB_UPDATED = "JOB_UPDATED"
    JOB_DELETED = "JOB_DELETED"
    JOB_APPLICATION_SUBMITTED = "JOB_APPLICATION_SUBMITTED"
    EMPLOYER_APPLICATIONS_RETRIEVED = "EMPLOYER_APPLICATIONS_RETRIEVED"

    # Event Type operations
    EVENT_TYPE_CREATED = "EVENT_TYPE_CREATED"
    EVENT_TYPE_RETRIEVED = "EVENT_TYPE_RETRIEVED"
    EVENT_TYPES_RETRIEVED = "EVENT_TYPES_RETRIEVED"
    EVENT_TYPE_UPDATED = "EVENT_TYPE_UPDATED"
    EVENT_TYPE_DELETED = "EVENT_TYPE_DELETED"
    EVENT_TYPE_RESTORED = "EVENT_TYPE_RESTORED"

    IMAGE_UPLOADED = "IMAGE_UPLOADED"
    IMAGE_DELETED = "IMAGE_DELETED"
    IMAGE_URL_RETRIEVED = "IMAGE_URL_RETRIEVED"

    # Survey/Question operations
    QUESTION_CREATED = "QUESTION_CREATED"
    QUESTION_RETRIEVED = "QUESTION_RETRIEVED"
    QUESTIONS_RETRIEVED = "QUESTIONS_RETRIEVED"
    QUESTION_UPDATED = "QUESTION_UPDATED"
    QUESTION_DELETED = "QUESTION_DELETED"
    QUESTION_RESTORED = "QUESTION_RESTORED"

    SURVEY_CREATED = "SURVEY_CREATED"
    SURVEY_RETRIEVED = "SURVEY_RETRIEVED"
    SURVEYS_RETRIEVED = "SURVEYS_RETRIEVED"
    SURVEY_UPDATED = "SURVEY_UPDATED"
    SURVEY_DELETED = "SURVEY_DELETED"
    SURVEY_RESTORED = "SURVEY_RESTORED"
    SURVEY_PUBLISHED = "SURVEY_PUBLISHED"
    SURVEY_CLOSED = "SURVEY_CLOSED"
    SURVEY_REOPENED = "SURVEY_REOPENED"

    SURVEY_QUESTION_ADDED = "SURVEY_QUESTION_ADDED"
    SURVEY_QUESTION_REMOVED = "SURVEY_QUESTION_REMOVED"
    SURVEY_QUESTIONS_RETRIEVED = "SURVEY_QUESTIONS_RETRIEVED"
    SURVEY_QUESTIONS_REORDERED = "SURVEY_QUESTIONS_REORDERED"
    SURVEY_QUESTIONS_BATCH_ADDED = "SURVEY_QUESTIONS_BATCH_ADDED"

    SURVEY_RESPONSE_SUBMITTED = "SURVEY_RESPONSE_SUBMITTED"
    SURVEY_RESPONSE_RETRIEVED = "SURVEY_RESPONSE_RETRIEVED"
    SURVEY_RESPONSES_RETRIEVED = "SURVEY_RESPONSES_RETRIEVED"
    SURVEY_RESULTS_RETRIEVED = "SURVEY_RESULTS_RETRIEVED"

    DISTRIBUTION_CONFIG_CREATED = "DISTRIBUTION_CONFIG_CREATED"
    DISTRIBUTION_CONFIG_RETRIEVED = "DISTRIBUTION_CONFIG_RETRIEVED"
    DISTRIBUTION_CONFIG_UPDATED = "DISTRIBUTION_CONFIG_UPDATED"
    DISTRIBUTION_INVITATIONS_SENT = "DISTRIBUTION_INVITATIONS_SENT"
    DISTRIBUTION_STATUS_RETRIEVED = "DISTRIBUTION_STATUS_RETRIEVED"
    DISTRIBUTION_NON_RESPONDENTS_RETRIEVED = "DISTRIBUTION_NON_RESPONDENTS_RETRIEVED"
    DISTRIBUTION_REMINDERS_SENT = "DISTRIBUTION_REMINDERS_SENT"

    # Prediction operations
    PREDICTION_COMPLETED = "PREDICTION_COMPLETED"
    PREDICTION_RETRIEVED = "PREDICTION_RETRIEVED"
    PREDICTIONS_RETRIEVED = "PREDICTIONS_RETRIEVED"

    # Regression prediction operations
    REGRESSION_PREDICTION_COMPLETED = "REGRESSION_PREDICTION_COMPLETED"
    REGRESSION_PREDICTION_RETRIEVED = "REGRESSION_PREDICTION_RETRIEVED"
    REGRESSION_PREDICTIONS_RETRIEVED = "REGRESSION_PREDICTIONS_RETRIEVED"

    # ARIMA forecast operations
    FORECAST_COMPLETED = "FORECAST_COMPLETED"
    FORECAST_RETRIEVED = "FORECAST_RETRIEVED"
    FORECASTS_RETRIEVED = "FORECASTS_RETRIEVED"

    # Model info operations
    MODEL_INFO_RETRIEVED = "MODEL_INFO_RETRIEVED"

    # Authentication
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
    TOKEN_VALIDATED = "TOKEN_VALIDATED"
    CURRENT_USER_RETRIEVED = "CURRENT_USER_RETRIEVED"

    # OTP operations
    OTP_SENT = "OTP_SENT"
    OTP_VERIFIED = "OTP_VERIFIED"
    OTP_RESENT = "OTP_RESENT"


class StandardResponse(BaseModel):
    """Standardized response wrapper for all API endpoints"""

    success: bool = Field(..., description="Whether the operation was successful")
    code: str = Field(..., description="Response code (ErrorCode or SuccessCode)")
    message: str = Field(..., description="Human-readable message")
    data: Optional[Any] = Field(default=None, description="Response data (optional)")
    timestamp: datetime = Field(
        default_factory=get_current_time_gmt8, description="Response timestamp in GMT+8"
    )

    @field_serializer("timestamp")
    def serialize_timestamp(self, value: datetime) -> str:
        """Serialize timestamp using the shared GMT+8 display format."""
        return format_datetime_gmt8(value)


class ErrorResponse(BaseModel):
    """Standardized error response"""

    code: ErrorCode
    message: str
